################################################################################
# Copyright (c) 2021,2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

name: Lint Charts

on:
  pull_request:
  workflow_call:
    inputs:
      helm_version:
        description: 'helm version to test (default = latest)'
        default: 'latest'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      helm_version:
        description: 'helm version to test (default = latest)'
        default: 'latest'
        required: false
        type: string

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for Release Version
        id: checkRelease
        run: |
          CHART_VERSION=$(grep 'version:' ./charts/bpdm/Chart.yaml | head -n1 | awk '{ print $2}')
          echo "CHART_VERSION: $CHART_VERSION"
          SNAPSHOT=$(echo "$CHART_VERSION" | grep 'SNAPSHOT' || echo "" )
          echo "SNAPSHOT: $SNAPSHOT"
          if [[ -z "$SNAPSHOT" ]]; then 
            IS_RELEASE=true 
          else 
            IS_RELEASE=false 
          fi
          echo "IS_RELEASE: $IS_RELEASE"
          echo "isRelease=$IS_RELEASE" >> $GITHUB_OUTPUT

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ github.event.inputs.helm_version || 'latest' }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Create Chart-Testing Config
        run: |
          cat <<EOF > .chart-testing-config.yaml
          validate-maintainers: false
          check-version-increment: ${{ steps.checkRelease.outputs.isRelease }}
          chart-repos:
            - bitnami=https://charts.bitnami.com/bitnami
          EOF
          echo "cat .chart-testing-config.yaml"
          cat .chart-testing-config.yaml

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --config .chart-testing-config.yaml
